/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package monthly.trading.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import monthly.trading.model.MonthlyTrading;
import monthly.trading.model.MonthlyTradingModel;
import monthly.trading.model.MonthlyTradingSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the MonthlyTrading service. Represents a row in the &quot;Banking_MonthlyTrading&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link MonthlyTradingModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MonthlyTradingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MonthlyTradingImpl
 * @see MonthlyTrading
 * @see MonthlyTradingModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class MonthlyTradingModelImpl extends BaseModelImpl<MonthlyTrading>
	implements MonthlyTradingModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a monthly trading model instance should use the {@link MonthlyTrading} interface instead.
	 */
	public static final String TABLE_NAME = "Banking_MonthlyTrading";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "monthlyTradingId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "year", Types.INTEGER },
			{ "month", Types.INTEGER },
			{ "volume", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("monthlyTradingId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("year", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("month", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("volume", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table Banking_MonthlyTrading (uuid_ VARCHAR(75) null,monthlyTradingId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,year INTEGER,month INTEGER,volume INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table Banking_MonthlyTrading";
	public static final String ORDER_BY_JPQL = " ORDER BY monthlyTrading.month ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Banking_MonthlyTrading.month ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(monthly.trading.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.monthly.trading.model.MonthlyTrading"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(monthly.trading.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.monthly.trading.model.MonthlyTrading"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(monthly.trading.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.monthly.trading.model.MonthlyTrading"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long YEAR_COLUMN_BITMASK = 8L;
	public static final long MONTH_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static MonthlyTrading toModel(MonthlyTradingSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		MonthlyTrading model = new MonthlyTradingImpl();

		model.setUuid(soapModel.getUuid());
		model.setMonthlyTradingId(soapModel.getMonthlyTradingId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setYear(soapModel.getYear());
		model.setMonth(soapModel.getMonth());
		model.setVolume(soapModel.getVolume());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<MonthlyTrading> toModels(MonthlyTradingSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<MonthlyTrading> models = new ArrayList<MonthlyTrading>(soapModels.length);

		for (MonthlyTradingSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(monthly.trading.service.util.ServiceProps.get(
				"lock.expiration.time.monthly.trading.model.MonthlyTrading"));

	public MonthlyTradingModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _monthlyTradingId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setMonthlyTradingId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _monthlyTradingId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return MonthlyTrading.class;
	}

	@Override
	public String getModelClassName() {
		return MonthlyTrading.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("monthlyTradingId", getMonthlyTradingId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("year", getYear());
		attributes.put("month", getMonth());
		attributes.put("volume", getVolume());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long monthlyTradingId = (Long)attributes.get("monthlyTradingId");

		if (monthlyTradingId != null) {
			setMonthlyTradingId(monthlyTradingId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Integer year = (Integer)attributes.get("year");

		if (year != null) {
			setYear(year);
		}

		Integer month = (Integer)attributes.get("month");

		if (month != null) {
			setMonth(month);
		}

		Integer volume = (Integer)attributes.get("volume");

		if (volume != null) {
			setVolume(volume);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getMonthlyTradingId() {
		return _monthlyTradingId;
	}

	@Override
	public void setMonthlyTradingId(long monthlyTradingId) {
		_monthlyTradingId = monthlyTradingId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getYear() {
		return _year;
	}

	@Override
	public void setYear(int year) {
		_columnBitmask |= YEAR_COLUMN_BITMASK;

		if (!_setOriginalYear) {
			_setOriginalYear = true;

			_originalYear = _year;
		}

		_year = year;
	}

	public int getOriginalYear() {
		return _originalYear;
	}

	@JSON
	@Override
	public int getMonth() {
		return _month;
	}

	@Override
	public void setMonth(int month) {
		_columnBitmask = -1L;

		_month = month;
	}

	@JSON
	@Override
	public int getVolume() {
		return _volume;
	}

	@Override
	public void setVolume(int volume) {
		_volume = volume;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				MonthlyTrading.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			MonthlyTrading.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public MonthlyTrading toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (MonthlyTrading)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		MonthlyTradingImpl monthlyTradingImpl = new MonthlyTradingImpl();

		monthlyTradingImpl.setUuid(getUuid());
		monthlyTradingImpl.setMonthlyTradingId(getMonthlyTradingId());
		monthlyTradingImpl.setGroupId(getGroupId());
		monthlyTradingImpl.setCompanyId(getCompanyId());
		monthlyTradingImpl.setUserId(getUserId());
		monthlyTradingImpl.setUserName(getUserName());
		monthlyTradingImpl.setCreateDate(getCreateDate());
		monthlyTradingImpl.setModifiedDate(getModifiedDate());
		monthlyTradingImpl.setYear(getYear());
		monthlyTradingImpl.setMonth(getMonth());
		monthlyTradingImpl.setVolume(getVolume());

		monthlyTradingImpl.resetOriginalValues();

		return monthlyTradingImpl;
	}

	@Override
	public int compareTo(MonthlyTrading monthlyTrading) {
		int value = 0;

		if (getMonth() < monthlyTrading.getMonth()) {
			value = -1;
		}
		else if (getMonth() > monthlyTrading.getMonth()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof MonthlyTrading)) {
			return false;
		}

		MonthlyTrading monthlyTrading = (MonthlyTrading)obj;

		long primaryKey = monthlyTrading.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		MonthlyTradingModelImpl monthlyTradingModelImpl = this;

		monthlyTradingModelImpl._originalUuid = monthlyTradingModelImpl._uuid;

		monthlyTradingModelImpl._originalGroupId = monthlyTradingModelImpl._groupId;

		monthlyTradingModelImpl._setOriginalGroupId = false;

		monthlyTradingModelImpl._originalCompanyId = monthlyTradingModelImpl._companyId;

		monthlyTradingModelImpl._setOriginalCompanyId = false;

		monthlyTradingModelImpl._setModifiedDate = false;

		monthlyTradingModelImpl._originalYear = monthlyTradingModelImpl._year;

		monthlyTradingModelImpl._setOriginalYear = false;

		monthlyTradingModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<MonthlyTrading> toCacheModel() {
		MonthlyTradingCacheModel monthlyTradingCacheModel = new MonthlyTradingCacheModel();

		monthlyTradingCacheModel.uuid = getUuid();

		String uuid = monthlyTradingCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			monthlyTradingCacheModel.uuid = null;
		}

		monthlyTradingCacheModel.monthlyTradingId = getMonthlyTradingId();

		monthlyTradingCacheModel.groupId = getGroupId();

		monthlyTradingCacheModel.companyId = getCompanyId();

		monthlyTradingCacheModel.userId = getUserId();

		monthlyTradingCacheModel.userName = getUserName();

		String userName = monthlyTradingCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			monthlyTradingCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			monthlyTradingCacheModel.createDate = createDate.getTime();
		}
		else {
			monthlyTradingCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			monthlyTradingCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			monthlyTradingCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		monthlyTradingCacheModel.year = getYear();

		monthlyTradingCacheModel.month = getMonth();

		monthlyTradingCacheModel.volume = getVolume();

		return monthlyTradingCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", monthlyTradingId=");
		sb.append(getMonthlyTradingId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", year=");
		sb.append(getYear());
		sb.append(", month=");
		sb.append(getMonth());
		sb.append(", volume=");
		sb.append(getVolume());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("monthly.trading.model.MonthlyTrading");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>monthlyTradingId</column-name><column-value><![CDATA[");
		sb.append(getMonthlyTradingId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>year</column-name><column-value><![CDATA[");
		sb.append(getYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>month</column-name><column-value><![CDATA[");
		sb.append(getMonth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>volume</column-name><column-value><![CDATA[");
		sb.append(getVolume());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = MonthlyTrading.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			MonthlyTrading.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _monthlyTradingId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _year;
	private int _originalYear;
	private boolean _setOriginalYear;
	private int _month;
	private int _volume;
	private long _columnBitmask;
	private MonthlyTrading _escapedModel;
}