/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package monthly.trading.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MonthlyTrading service. Represents a row in the &quot;Banking_MonthlyTrading&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link monthly.trading.model.impl.MonthlyTradingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link monthly.trading.model.impl.MonthlyTradingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see MonthlyTrading
 * @see monthly.trading.model.impl.MonthlyTradingImpl
 * @see monthly.trading.model.impl.MonthlyTradingModelImpl
 * @generated
 */
@ProviderType
public interface MonthlyTradingModel extends BaseModel<MonthlyTrading>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a monthly trading model instance should use the {@link MonthlyTrading} interface instead.
	 */

	/**
	 * Returns the primary key of this monthly trading.
	 *
	 * @return the primary key of this monthly trading
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this monthly trading.
	 *
	 * @param primaryKey the primary key of this monthly trading
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this monthly trading.
	 *
	 * @return the uuid of this monthly trading
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this monthly trading.
	 *
	 * @param uuid the uuid of this monthly trading
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the monthly trading ID of this monthly trading.
	 *
	 * @return the monthly trading ID of this monthly trading
	 */
	public long getMonthlyTradingId();

	/**
	 * Sets the monthly trading ID of this monthly trading.
	 *
	 * @param monthlyTradingId the monthly trading ID of this monthly trading
	 */
	public void setMonthlyTradingId(long monthlyTradingId);

	/**
	 * Returns the group ID of this monthly trading.
	 *
	 * @return the group ID of this monthly trading
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this monthly trading.
	 *
	 * @param groupId the group ID of this monthly trading
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this monthly trading.
	 *
	 * @return the company ID of this monthly trading
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this monthly trading.
	 *
	 * @param companyId the company ID of this monthly trading
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this monthly trading.
	 *
	 * @return the user ID of this monthly trading
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this monthly trading.
	 *
	 * @param userId the user ID of this monthly trading
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this monthly trading.
	 *
	 * @return the user uuid of this monthly trading
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this monthly trading.
	 *
	 * @param userUuid the user uuid of this monthly trading
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this monthly trading.
	 *
	 * @return the user name of this monthly trading
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this monthly trading.
	 *
	 * @param userName the user name of this monthly trading
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this monthly trading.
	 *
	 * @return the create date of this monthly trading
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this monthly trading.
	 *
	 * @param createDate the create date of this monthly trading
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this monthly trading.
	 *
	 * @return the modified date of this monthly trading
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this monthly trading.
	 *
	 * @param modifiedDate the modified date of this monthly trading
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the year of this monthly trading.
	 *
	 * @return the year of this monthly trading
	 */
	public int getYear();

	/**
	 * Sets the year of this monthly trading.
	 *
	 * @param year the year of this monthly trading
	 */
	public void setYear(int year);

	/**
	 * Returns the month of this monthly trading.
	 *
	 * @return the month of this monthly trading
	 */
	public int getMonth();

	/**
	 * Sets the month of this monthly trading.
	 *
	 * @param month the month of this monthly trading
	 */
	public void setMonth(int month);

	/**
	 * Returns the volume of this monthly trading.
	 *
	 * @return the volume of this monthly trading
	 */
	public int getVolume();

	/**
	 * Sets the volume of this monthly trading.
	 *
	 * @param volume the volume of this monthly trading
	 */
	public void setVolume(int volume);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(monthly.trading.model.MonthlyTrading monthlyTrading);

	@Override
	public int hashCode();

	@Override
	public CacheModel<monthly.trading.model.MonthlyTrading> toCacheModel();

	@Override
	public monthly.trading.model.MonthlyTrading toEscapedModel();

	@Override
	public monthly.trading.model.MonthlyTrading toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}