/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package monthly.trading.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import monthly.trading.model.MonthlyTrading;

import monthly.trading.service.MonthlyTradingLocalService;
import monthly.trading.service.persistence.MonthlyTradingPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the monthly trading local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link monthly.trading.service.impl.MonthlyTradingLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see monthly.trading.service.impl.MonthlyTradingLocalServiceImpl
 * @see monthly.trading.service.MonthlyTradingLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class MonthlyTradingLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements MonthlyTradingLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link monthly.trading.service.MonthlyTradingLocalServiceUtil} to access the monthly trading local service.
	 */

	/**
	 * Adds the monthly trading to the database. Also notifies the appropriate model listeners.
	 *
	 * @param monthlyTrading the monthly trading
	 * @return the monthly trading that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MonthlyTrading addMonthlyTrading(MonthlyTrading monthlyTrading) {
		monthlyTrading.setNew(true);

		return monthlyTradingPersistence.update(monthlyTrading);
	}

	/**
	 * Creates a new monthly trading with the primary key. Does not add the monthly trading to the database.
	 *
	 * @param monthlyTradingId the primary key for the new monthly trading
	 * @return the new monthly trading
	 */
	@Override
	public MonthlyTrading createMonthlyTrading(long monthlyTradingId) {
		return monthlyTradingPersistence.create(monthlyTradingId);
	}

	/**
	 * Deletes the monthly trading with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param monthlyTradingId the primary key of the monthly trading
	 * @return the monthly trading that was removed
	 * @throws PortalException if a monthly trading with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MonthlyTrading deleteMonthlyTrading(long monthlyTradingId)
		throws PortalException {
		return monthlyTradingPersistence.remove(monthlyTradingId);
	}

	/**
	 * Deletes the monthly trading from the database. Also notifies the appropriate model listeners.
	 *
	 * @param monthlyTrading the monthly trading
	 * @return the monthly trading that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public MonthlyTrading deleteMonthlyTrading(MonthlyTrading monthlyTrading) {
		return monthlyTradingPersistence.remove(monthlyTrading);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(MonthlyTrading.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return monthlyTradingPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link monthly.trading.model.impl.MonthlyTradingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return monthlyTradingPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link monthly.trading.model.impl.MonthlyTradingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return monthlyTradingPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return monthlyTradingPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return monthlyTradingPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public MonthlyTrading fetchMonthlyTrading(long monthlyTradingId) {
		return monthlyTradingPersistence.fetchByPrimaryKey(monthlyTradingId);
	}

	/**
	 * Returns the monthly trading matching the UUID and group.
	 *
	 * @param uuid the monthly trading's UUID
	 * @param groupId the primary key of the group
	 * @return the matching monthly trading, or <code>null</code> if a matching monthly trading could not be found
	 */
	@Override
	public MonthlyTrading fetchMonthlyTradingByUuidAndGroupId(String uuid,
		long groupId) {
		return monthlyTradingPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the monthly trading with the primary key.
	 *
	 * @param monthlyTradingId the primary key of the monthly trading
	 * @return the monthly trading
	 * @throws PortalException if a monthly trading with the primary key could not be found
	 */
	@Override
	public MonthlyTrading getMonthlyTrading(long monthlyTradingId)
		throws PortalException {
		return monthlyTradingPersistence.findByPrimaryKey(monthlyTradingId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(monthlyTradingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MonthlyTrading.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("monthlyTradingId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(monthlyTradingLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(MonthlyTrading.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"monthlyTradingId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(monthlyTradingLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(MonthlyTrading.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("monthlyTradingId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<MonthlyTrading>() {
				@Override
				public void performAction(MonthlyTrading monthlyTrading)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						monthlyTrading);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(MonthlyTrading.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return monthlyTradingLocalService.deleteMonthlyTrading((MonthlyTrading)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return monthlyTradingPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the monthly tradings matching the UUID and company.
	 *
	 * @param uuid the UUID of the monthly tradings
	 * @param companyId the primary key of the company
	 * @return the matching monthly tradings, or an empty list if no matches were found
	 */
	@Override
	public List<MonthlyTrading> getMonthlyTradingsByUuidAndCompanyId(
		String uuid, long companyId) {
		return monthlyTradingPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of monthly tradings matching the UUID and company.
	 *
	 * @param uuid the UUID of the monthly tradings
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of monthly tradings
	 * @param end the upper bound of the range of monthly tradings (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching monthly tradings, or an empty list if no matches were found
	 */
	@Override
	public List<MonthlyTrading> getMonthlyTradingsByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<MonthlyTrading> orderByComparator) {
		return monthlyTradingPersistence.findByUuid_C(uuid, companyId, start,
			end, orderByComparator);
	}

	/**
	 * Returns the monthly trading matching the UUID and group.
	 *
	 * @param uuid the monthly trading's UUID
	 * @param groupId the primary key of the group
	 * @return the matching monthly trading
	 * @throws PortalException if a matching monthly trading could not be found
	 */
	@Override
	public MonthlyTrading getMonthlyTradingByUuidAndGroupId(String uuid,
		long groupId) throws PortalException {
		return monthlyTradingPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the monthly tradings.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link monthly.trading.model.impl.MonthlyTradingModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of monthly tradings
	 * @param end the upper bound of the range of monthly tradings (not inclusive)
	 * @return the range of monthly tradings
	 */
	@Override
	public List<MonthlyTrading> getMonthlyTradings(int start, int end) {
		return monthlyTradingPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of monthly tradings.
	 *
	 * @return the number of monthly tradings
	 */
	@Override
	public int getMonthlyTradingsCount() {
		return monthlyTradingPersistence.countAll();
	}

	/**
	 * Updates the monthly trading in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param monthlyTrading the monthly trading
	 * @return the monthly trading that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public MonthlyTrading updateMonthlyTrading(MonthlyTrading monthlyTrading) {
		return monthlyTradingPersistence.update(monthlyTrading);
	}

	/**
	 * Returns the monthly trading local service.
	 *
	 * @return the monthly trading local service
	 */
	public MonthlyTradingLocalService getMonthlyTradingLocalService() {
		return monthlyTradingLocalService;
	}

	/**
	 * Sets the monthly trading local service.
	 *
	 * @param monthlyTradingLocalService the monthly trading local service
	 */
	public void setMonthlyTradingLocalService(
		MonthlyTradingLocalService monthlyTradingLocalService) {
		this.monthlyTradingLocalService = monthlyTradingLocalService;
	}

	/**
	 * Returns the monthly trading persistence.
	 *
	 * @return the monthly trading persistence
	 */
	public MonthlyTradingPersistence getMonthlyTradingPersistence() {
		return monthlyTradingPersistence;
	}

	/**
	 * Sets the monthly trading persistence.
	 *
	 * @param monthlyTradingPersistence the monthly trading persistence
	 */
	public void setMonthlyTradingPersistence(
		MonthlyTradingPersistence monthlyTradingPersistence) {
		this.monthlyTradingPersistence = monthlyTradingPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("monthly.trading.model.MonthlyTrading",
			monthlyTradingLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"monthly.trading.model.MonthlyTrading");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return MonthlyTradingLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return MonthlyTrading.class;
	}

	protected String getModelClassName() {
		return MonthlyTrading.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = monthlyTradingPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = MonthlyTradingLocalService.class)
	protected MonthlyTradingLocalService monthlyTradingLocalService;
	@BeanReference(type = MonthlyTradingPersistence.class)
	protected MonthlyTradingPersistence monthlyTradingPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}